#!/usr/bin/env python3
"""Capture an exact Python environment snapshot for experiment provenance."""

from __future__ import annotations

import argparse
import platform
import subprocess
import sys
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    freeze = subprocess.run(
        [sys.executable, "-m", "pip", "freeze", "--all"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.rstrip()

    try:
        import torch

        torch_version = torch.__version__
        torch_cuda = torch.version.cuda
    except ImportError:
        torch_version = "not-installed"
        torch_cuda = "not-installed"

    header = [
        "# Generated by scripts/capture_environment.py",
        f"# python={platform.python_version()}",
        f"# platform={platform.platform()}",
        f"# torch={torch_version}",
        f"# torch_cuda={torch_cuda}",
        "# Local editable paths record provenance and may require relocation.",
    ]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        "\n".join(header) + "\n" + freeze + "\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
